name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Gradle
      run: ./gradlew build
        
    - name: Publish Test Results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: results.sarif
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    
    - name: Publish Test Results as Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN}}
        publish_dir: ./build/reports/tests/test/

    
