name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
    
jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
                 
    - name: Test with Gradle
      run: ./gradlew test
      env:
        TEST_REPORTS: ${{github.workspace}}/build/test-results/test
        
    # Upload test results as an artifact
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Test results
        path: ${{github.workspace}}/build/test-results/test
